# Generated by Django 5.1.5 on 2025-02-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.JSONField(max_length=20, null=True, unique=True)),
                ('unlocs', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('alias', models.JSONField(blank=True, default=list)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('coordinates', models.JSONField(blank=True, default=list)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
